### ISSUE TITLE
utf8_range's cmake build doesn't support installing pkgconfig .pc file (breaks pkgconfig for downstream projects)

### ISSUE THREAD

**Issue by jtattermusch** [protocolbuffers/utf8_range#20]
Unlike protobuf, grpc and other projects that depend on utf8_range, the library's cmake build doesn't support installing the pkgconfig .pc file as part of cmake install.

That basically prevents downstream projects from providing their own .pc pkgconfig files as part of their install cleanly, since e.g. protobuf starting from version 22.x now depends on utf8_validity (and that dependency should be declareded in protobuf.pc when installed).

This issue breaks grpc's build-and-install "distribtest" that tries to build helloworld example with grpc and protobuf:
https://github.com/grpc/grpc/blob/24d83cda9bb1caaff9c03ace6f418e946e88c49d/examples/cpp/helloworld/Makefile#L28

**Comment by jtattermusch** [comment]
CC @deannagarcia @mkruskal-google  I have a dirty workaround I can use in our distribtests so fixing this isn't a strict blocker for grpc's protobuf 22.x upgrade, but of course this is something that still needs to be fixed in order for building via pkgconfig to become clean again.

**Comment by carlocab** [comment]
It looks like this was fixed in 3f179d13427978e652e72fa4584c55e5b1528493.

**Comment by mkruskal-google** [comment]
Thanks for pinging this Carlo, there was a duplicate issue I marked on that PR
